### ISSUE TITLE
Grueneisen parameter

### ISSUE THREAD

**Issue by sannecottaar** [geodynamics/burnman#249]
mineral.py includes:
    @material_property
    @copy_documentation(Material.grueneisen_parameter)
    def grueneisen_parameter(self):
        if self.temperature < 1.e-12:
            return 0.
        else:
            return self.thermal_expansivity \* self.isothermal_bulk_modulus \
                \* self.molar_volume / self.heat_capacity_v

This actually means the many (differently) implemented grueneisen parameters in the eos's are not being called. I think we should just change this to self.method.grueneisen_parameter(..). Agreed?

**Comment by bobmyhill** [comment]
Good catch! 

I think you're probably correct, given that grueneisen is sometimes a derived parameter but at others an input. 

After the change, could there be a note in the documentation to the effect that gr is implemented in every mineral model, but should always equal alpha*K_T*V/C_v?

**Comment by sannecottaar** [comment]
We could also take it out of the EoSs? If you think that is better.

**Comment by bobmyhill** [comment]
The issue is that sometimes there will be a need for a Grueneisen function in the EoS (SLB2011, for example), so we couldn't consistently remove it. I suppose we could make it an internal function, but I'm not sure that's cleaner than what we have already. I'd probably favour changing mineral.py to self.method.grueneisen_parameter(..) as you suggested, with a brief reminder that gr == alpha*K_T*V/C_v.
